version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: Qubit
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db 
    networks:
      - mongo_network

volumes:
  mongodb-data:

networks:
  mongo_network:
    driver: bridge
